name: Summator unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  summator-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore Summator
      - run: dotnet build Summator --no-restore
      - run: dotnet test Summator --no-build --verbosity normal
      - run: dotnet restore SummatorWithPOM/SummatorWithPOM
      - run: dotnet build SummatorWithPOM/SummatorWithPOM --no-restore
      - run: dotnet test SummatorWithPOM/SummatorWithPOM --no-build --verbosity normal
