name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      working-directory: ./Summator
      run: dotnet restore
    - name: Build
      working-directory: ./Summator
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Summator
      run: dotnet test --no-build --verbosity normal
